# Generated by Django 4.0.4 on 2022-05-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('difficulty', models.SmallIntegerField(choices=[(1, 'Hard'), (2, 'Medium'), (3, 'Easy')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('inputData', models.CharField(max_length=30)),
                ('outoputData', models.CharField(max_length=30)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problemdetail', to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
