# Generated by Django 4.0.4 on 2022-05-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemdetail',
            old_name='outoputData',
            new_name='outputData',
        ),
    ]
