# Generated by Django 4.0.4 on 2022-05-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_outoputdata_problemdetail_outputdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemdetail',
            name='inputData',
        ),
        migrations.RemoveField(
            model_name='problemdetail',
            name='outputData',
        ),
    ]
