# Generated by Django 4.0.4 on 2022-05-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example', to='problems.problem'),
        ),
    ]
