# Generated by Django 4.0.4 on 2022-05-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_example_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemDetail',
        ),
    ]
