# Generated by Django 4.0.4 on 2022-05-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_delete_problemdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ornek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
                ('inputData', models.CharField(max_length=30)),
                ('outputData', models.CharField(max_length=30)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ornek', to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
