# Generated by Django 4.0.4 on 2022-05-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_ornek_delete_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ornek',
            new_name='Example',
        ),
    ]
