# Generated by Django 4.0.4 on 2022-05-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_rename_ornek_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now=True)),
                ('update_data', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problemdetail', to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
