# Generated by Django 4.0.4 on 2022-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_backtestexample'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Problems',
        ),
    ]
