# Generated by Django 4.0.4 on 2022-05-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_rename_problem_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example', to='problems.problems'),
        ),
    ]
